### ISSUE TITLE
In Universal example issue with ongoingContext$ in app.js file...

### ISSUE THREAD

**Issue by Cmdv** [cyclejs/cycle-history#2]
so after using the Universal / Isomorphic example from link [here](https://github.com/cyclejs/cycle-examples/tree/master/isomorphic) and adding cycle-history I get an issue in app.js on this [line](https://github.com/cyclejs/cycle-examples/blob/master/isomorphic/app.js#L42)
```javascript
let routeFromClick$ = ext.DOM.select('.link').events('click')
    .doOnNext(ev => ev.preventDefault())
    .map(ev => ev.currentTarget.attributes.href.value);

let ongoingContext$ = ext.context
// this line bellow is throwing the error
    .merge(routeFromClick$).scan((acc, x) => {
      acc.route = x;
      return acc;
    });
```
```javascript
TypeError: Cannot read property 'merge' of undefined
```

Not entirely sure if the app.js function needs to also change?

**Comment by Cmdv** [comment]
ps [here](https://github.com/Cmdv/cycle-experiment) is my repo, I've split files out to try make it more like a production app ready fro expansion. :)

**Comment by TylorS** [comment]
Is it safe for me to go ahead and close this? I feel as though most problems should have been addressed in `cycle-starter`?

**Comment by Cmdv** [comment]
yes of course sorry I missed this on my feed! I'll close it :smiley:
