### ISSUE TITLE
Same history instance for HistoryDriver and ReactRouter

### ISSUE THREAD

**Issue by vladap** [cyclejs/cycle-history#6]
Hi,
great work. I use Cycle as a replacement to Flux in my React App which uses ReactRouter. I would like to use HistoryDriver so that I can change history state or react to history changes in my services (models) (independent from React).

I assume that I need the same history instance for both and there is no way how to get or set history instance in HistoryDriver.

It would help if I could provide history instance when creating HistoryDriver. Probably by changing to function makeHistoryDriver(config, history) { ... }?

**Comment by TylorS** [comment]
Hmmm, that's a use-case I hadn't considered before. I think it would be safe to place it right inside of the config.
```js
makeHistoryDriver({
  hash: true,
  history: createHistory(.....)
})
```

Then if it's present skip creating it internally. What do you think?

**Comment by vladap** [comment]
It would be fine, I think even better.

I tried a quick hack on forked code and react-router doesn't react to history changes even it shares the same history instance. But I think I'm doing something wrong, based on https://github.com/rackt/react-router/blob/v1.0.3/docs/guides/advanced/NavigatingOutsideOfComponents.md, it should work. I need to put some more time. It doesn't look like there is any blocker inside of HistoryDriver, looking at the src. Location gets changed in browser bar.

**Comment by TylorS** [comment]
Yeah, this driver should have a care in the world about where the route changes come from. 
Feel free to ask any question. I'll gladly help if I can.

**Comment by vladap** [comment]
Today it works while I changed nothing, haha.

I just added this simple code:
const history = config.history ?
    config.history :
    makeHistory(hash, queries, options)

I think it is too much hassle to go through my own PR, hence if you think it is beneficial to add it (or any variant as seen fit) feel free to do so at some point.

Many thanks for your help

**Comment by vladap** [comment]
I have finally managed to create PR for it.

**Comment by TylorS** [comment]
Merged, I'll push to NPM shortly.
